### ISSUE TITLE
Mi.php  context = null

### ISSUE THREAD

**Issue by wuchuguang** [pinguo/php-msf#85]
```
/**
     * 通过对象池生成对象
     *
     * @param array $args
     * @return \stdClass|mixed
     */
    public function getObject(...$args)
    {
       //请求间隔久时，这里会出现this->context = null的情况。Miner过来的getObject(Mysql::class,...)
        return $this->context->getObjectPool()->get(...$args);
    }
```

**Comment by xudianyang** [comment]
这个问题还能复现吗？

**Comment by qxhy123** [comment]
这个问题不但能复现, 而且是百分百复现, 请求间隔久没试过, 但是频繁访问下绝对会出现, 假设有控制器A和控制器B, 两个控制器Index方法都有数据库连接操作, 连续请求控制器A多次, 然后立刻请求控制器B多次, 交替一次或者多次之后就会出现call member method getObjectPool on null, 经过大量调试排查问题应该是出在控制器销毁对象那里, 分析原因可能是因为之前的请求尚未处理完成, 从查看monitor可以看到worker下coroutine数量不为0, 但是实际上这些coroutine在某个时间点已经执行完毕, 没有回收, 或者回收不完全, 总之这些coroutine一直存在, 新的请求进来之后被错乱的对象销毁机制销毁掉了context属性, 最终导致Miner的go方法调用失败报错, 目前的解决方案是移除controller控制器destroy方法中销毁对象的几行代码, 然后在Scheduler类的检测coroutine超时的方法中检测task->getRoutine是否为null, 如果为null, 强行调用task的destroy方法, 目前观察内存没有暴涨, 也没有再出现过context突然变成null的问题.

**Comment by braylog** [comment]
[logid:5c18f9ce78c5d704876ce461] Error: Call to a member function getObjectPool() on null in /home/wwwroot/video.qqc.com/vendor/pinguo/php-aop/src/MI.php:56 Stack trace: #0 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/Pools/Miner.php(1932): PG\MSF\Pools\Miner->getObject('PG\\MSF\\Coroutin...', Array) #1 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/Proxy/MysqlProxyMasterSlave.php(152): PG\MSF\Pools\Miner->go() #2 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/Base/AOPFactory.php(61): PG\MSF\Proxy\MysqlProxyMasterSlave->handle('go', Array) #3 /home/wwwroot/video.qqc.com/vendor/pinguo/php-aop/src/Wrapper.php(86): PG\MSF\Base\AOPFactory::PG\MSF\Base\{closure}('go', Array) #4 /home/wwwroot/video.qqc.com/app/Models/DAO/Front/Video.php(55): PG\AOP\Wrapper->__call('go', Array) #5 [internal function]: App\Models\DAO\Front\Video->getVideos(Array, Array, Array) #6 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/Coroutine/Scheduler.php(109): Generator->valid() #7 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/Coroutine/Scheduler.php(115): PG\MSF\Coroutine\Scheduler->schedule(Object(PG\MSF\Coroutine\Task)) #8 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/Coroutine/Base.php(145): PG\MSF\Coroutine\Scheduler->schedule(Object(PG\MSF\Coroutine\Task)) #9 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/Coroutine/MySql.php(72): PG\MSF\Coroutine\Base->nextRun() #10 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/Pools/AsynPool.php(135): PG\MSF\Coroutine\MySql->PG\MSF\Coroutine\{closure}(Array) #11 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/Pools/AsynPoolManager.php(154): PG\MSF\Pools\AsynPool->distribute(Array) #12 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/Pools/MysqlAsynPool.php(148): PG\MSF\Pools\AsynPoolManager->sendMessageToWorker(Object(PG\MSF\Pools\MysqlAsynPool), Array) #13 [internal function]: PG\MSF\Pools\MysqlAsynPool->PG\MSF\Pools\{closure}(Object(swoole_mysql), Array) #14 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/HttpServer.php(158): swoole_http_server->start() #15 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/MSFServer.php(91): PG\MSF\HttpServer->start() #16 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/Server.php(500): PG\MSF\MSFServer->start() #17 /home/wwwroot/video.qqc.com/vendor/pinguo/php-msf/src/Server.php(270): PG\MSF\Server::startSwooles() #18 /home/wwwroot/video.qqc.com/server.php(22): PG\MSF\Server::run() #19 {main}

**Comment by alenzzzz** [comment]
> 



> 这个问题不但能复现, 而且是百分百复现, 请求间隔久没试过, 但是频繁访问下绝对会出现, 假设有控制器A和控制器B, 两个控制器Index方法都有数据库连接操作, 连续请求控制器A多次, 然后立刻请求控制器B多次, 交替一次或者多次之后就会出现call member method getObjectPool on null, 经过大量调试排查问题应该是出在控制器销毁对象那里, 分析原因可能是因为之前的请求尚未处理完成, 从查看monitor可以看到worker下coroutine数量不为0, 但是实际上这些coroutine在某个时间点已经执行完毕, 没有回收, 或者回收不完全, 总之这些coroutine一直存在, 新的请求进来之后被错乱的对象销毁机制销毁掉了context属性, 最终导致Miner的go方法调用失败报错, 目前的解决方案是移除controller控制器destroy方法中销毁对象的几行代码, 然后在Scheduler类的检测coroutine超时的方法中检测task->getRoutine是否为null, 如果为null, 强行调用task的destroy方法, 目前观察内存没有暴涨, 也没有再出现过context突然变成null的问题.

hi @qxhy123 

在我当前负责的项目中，发现了类似的问题，请问你是否是通过调整下述代码解决了问题

![image](https://user-images.githubusercontent.com/22517748/143669265-d216feb6-ecae-4cbe-8caf-c383e6a1b133.png)
![image](https://user-images.githubusercontent.com/22517748/143669281-2f57170e-0bd3-4955-a420-11cbc1b59fe9.png)

希望你可以帮忙解答，非常感谢
